<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [Legato]" duration-ms="14330" started-at="2020-07-14T11:10:14Z" finished-at="2020-07-14T11:10:28Z">
    <groups>
    </groups>
    <test name="ITMS_APP(failed)" duration-ms="14330" started-at="2020-07-14T11:10:14Z" finished-at="2020-07-14T11:10:28Z">
      <class name="com.Legato.testCases.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.Legato.testCases.LoginTest@4883b407]" name="setUp" is-config="true" duration-ms="2545" started-at="2020-07-14T11:10:14Z" finished-at="2020-07-14T11:10:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:com.Legato.testCases.LoginTest@4883b407]" name="loginTest" duration-ms="10757" started-at="2020-07-14T11:10:17Z" finished-at="2020-07-14T11:10:27Z">
          <exception class="java.io.IOException">
            <message>
              <![CDATA[Source 'C:\Users\HARISH~1.LIN\AppData\Local\Temp\screenshot612624249886572480.png' exists but is not a directory]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.IOException: Source 'C:\Users\HARISH~1.LIN\AppData\Local\Temp\screenshot612624249886572480.png' exists but is not a directory
at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1371)
at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1261)
at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1230)
at com.Legato.testCases.BaseClass.captureScreen(BaseClass.java:47)
at com.Legato.testCases.LoginTest.loginTest(LoginTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.IOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.Legato.testCases.LoginTest@4883b407]" name="tearDown" is-config="true" duration-ms="766" started-at="2020-07-14T11:10:27Z" finished-at="2020-07-14T11:10:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.Legato.testCases.LoginTest -->
    </test> <!-- ITMS_APP(failed) -->
  </suite> <!-- Failed suite [Legato] -->
</testng-results>
